In [37]:
import numpy as np
import pandas as pd
import random
import json

In [38]:
pd.set_option('display.max_columns', None)

In [39]:
df = pd.read_parquet("../data/lol_database_full.parquet.gzip", engine = "fastparquet")
df.head()

,Trn ID,Trn Name,Stage,Section,trn_recent_world_msi_region_22_23,league_score,Team ID,Team Name,Team Acronym,Team Slug,useful_team_indicator,Game ID,Outcome,day,month,year,event_date,totalGold_own,championsKills_own,xp_own_avg,level_own_avg,level_opp_avg,attackSpeed_own_avg
0,110733838935136200,#2 Summer 2023,Groups,Group A,0,39.8876,109981650516317055,Mirage Alliance,MIR,mirage-alliance,0,110733838936446929,1,22,7,2023,2023-07-22,53655,22,11901.599609,13.8,12.2,185.199997
1,110733838935136200,#2 Summer 2023,Groups,Group A,0,39.8876,110733889090164854,Return of the Middlesticks,ROTM,return-of-the-middlesticks,0,110733838936446929,0,22,7,2023,2023-07-22,41352,7,9459.000000,12.2,13.8,155.199997
2,110733838935136200,#2 Summer 2023,Groups,Group A,0,39.8876,110733889090164854,Return of the Middlesticks,ROTM,return-of-the-middlesticks,0,110733838936446930,0,22,7,2023,2023-07-22,50115,14,11809.400391,13.4,14.2,207.600006
3,110733838935136200,#2 Summer 2023,Groups,Group A,0,39.8876,109981650516317055,Mirage Alliance,MIR,mirage-alliance,0,110733838936446930,1,22,7,2023,2023-07-22,55269,16,12480.799805,14.2,13.4,177.600006
4,110733838935136200,#2 Summer 2023,Groups,Group A,0,39.8876,110733877357854829,Gentle Hearts Gaming,GHG,gentle-hearts-gaming,0,110733838936446933,1,22,7,2023,2023-07-22,54092,24,12234.000000,14.0,12.0,158.199997

In [41]:
df.loc[df['Trn ID'] == 105562822074055437]

,Trn ID,Trn Name,Stage,Section,trn_recent_world_msi_region_22_23,league_score,Team ID,Team Name,Team Acronym,Team Slug,useful_team_indicator,Game ID,Outcome,day,month,year,event_date,totalGold_own,championsKills_own,xp_own_avg,level_own_avg,level_opp_avg,attackSpeed_own_avg
42762,105562822074055437,TCL Winter 2021,Regular Season,Regular Season,0,30.337099,98767991949608898,Fenerbahçe Espor,FB,fenerbahce-espor,0,105562822076218129,1,31,1,2021,2021-01-31,62111,19,15141.200195,15.6,13.6,174.800003
42763,105562822074055437,TCL Winter 2021,Regular Season,Regular Season,0,30.337099,103495716836203404,5 Ronin,5R,5-ronin,0,105562822076218129,0,31,1,2021,2021-01-31,49435,8,11979.400391,13.6,15.6,164.399994
42764,105562822074055437,TCL Winter 2021,Regular Season,Regular Season,0,30.337099,98767991949608898,Fenerbahçe Espor,FB,fenerbahce-espor,0,105562822076218131,1,20,3,2021,2021-03-20,49078,7,11841.599609,13.8,14.8,191.399994
42765,105562822074055437,TCL Winter 2021,Regular Season,Regular Season,0,30.337099,103495716886587312,Beşiktaş,BJK,besiktas,0,105562822076218131,0,20,3,2021,2021-03-20,53972,12,13421.799805,14.8,13.8,189.000000
42766,105562822074055437,TCL Winter 2021,Regular Season,Regular Season,0,30.337099,99566406065437842,Dark Passage,DP,dark-passage,0,105562822076218133,0,21,3,2021,2021-03-21,49933,9,12046.799805,13.8,15.8,153.199997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42983,105562822074055437,TCL Winter 2021,Playoffs,Playoffs,0,50.561798,102235771678061291,DenizBank İstanbul Wildcats,IW,fastpay-wildcats,1,105788375893721920,1,17,4,2021,2021-04-17,42135,18,9286.000000,12.0,10.6,150.600006
42984,105562822074055437,TCL Winter 2021,Playoffs,Playoffs,0,50.561798,102235771678061291,DenizBank İstanbul Wildcats,IW,fastpay-wildcats,1,105788375893721921,1,17,4,2021,2021-04-17,64513,13,15749.400391,15.8,17.0,146.000000
42985,105562822074055437,TCL Winter 2021,Playoffs,Playoffs,0,50.561798,98767991949608898,Fenerbahçe Espor,FB,fenerbahce-espor,0,105788375893721921,0,17,4,2021,2021-04-17,73945,25,17169.000000,17.0,15.8,193.800003
42986,105562822074055437,TCL Winter 2021,Playoffs,Playoffs,0,50.561798,98767991949608898,Fenerbahçe Espor,FB,fenerbahce-espor,0,105788375893721922,0,17,4,2021,2021-04-17,55694,17,13157.599609,14.4,13.2,182.600006
42987,105562822074055437,TCL Winter 2021,Playoffs,Playoffs,0,50.561798,102235771678061291,DenizBank İstanbul Wildcats,IW,fastpay-wildcats,1,105788375893721922,1,17,4,2021,2021-04-17,47139,9,10981.000000,13.2,14.4,158.600006

In [40]:
df.loc[df['Trn Name'].str.contains('Worlds 2022')]

,Trn ID,Trn Name,Stage,Section,trn_recent_world_msi_region_22_23,league_score,Team ID,Team Name,Team Acronym,Team Slug,useful_team_indicator,Game ID,Outcome,day,month,year,event_date,totalGold_own,championsKills_own,xp_own_avg,level_own_avg,level_opp_avg,attackSpeed_own_avg
19682,108998961191900167,Worlds 2022,Play In Groups,Group A,1,50.561798,100285330168091787,DetonatioN FocusMe,DFM,detonation-focusme,1,108998961197667353,0,30,9,2022,2022-09-30,35465,5,8148.600098,11.200000,13.000000,141.600006
19683,108998961191900167,Worlds 2022,Play In Groups,Group A,1,50.561798,105397404796640412,LOUD,LLL,loud,1,108998961197667353,1,30,9,2022,2022-09-30,46848,21,10769.400391,13.000000,11.200000,160.199997
19684,108998961191900167,Worlds 2022,Play In Groups,Group A,1,50.561798,103461966951059521,Evil Geniuses LG,EG,evil-geniuses,1,108998961199109147,1,30,9,2022,2022-09-30,66402,25,15645.000000,16.200001,14.600000,195.199997
19685,108998961191900167,Worlds 2022,Play In Groups,Group A,1,50.561798,105397404796640412,LOUD,LLL,loud,1,108998961199109147,0,30,9,2022,2022-09-30,57069,13,13128.000000,14.600000,16.200001,176.800003
19686,108998961191900167,Worlds 2022,Play In Groups,Group A,1,50.561798,105397404796640412,LOUD,LLL,loud,1,108998961199109149,1,2,10,2022,2022-10-02,60464,29,13158.000000,14.600000,14.000000,194.600006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19927,108998961191900167,Worlds 2022,knockouts,knockouts,1,53.932598,99566404585387054,DRX,DRX,drx,1,108998961199895795,0,6,11,2022,2022-11-06,53807,12,12686.400391,14.200000,15.000000,171.800003
19928,108998961191900167,Worlds 2022,knockouts,knockouts,1,53.932598,99566404585387054,DRX,DRX,drx,1,108998961199895796,1,6,11,2022,2022-11-06,54750,14,12981.000000,14.400000,13.000000,200.800003
19929,108998961191900167,Worlds 2022,knockouts,knockouts,1,53.932598,98767991853197861,T1,T1,t1,1,108998961199895796,0,6,11,2022,2022-11-06,46383,4,11090.400391,13.000000,14.400000,166.399994
19930,108998961191900167,Worlds 2022,knockouts,knockouts,1,53.932598,98767991853197861,T1,T1,t1,1,108998961199895797,0,6,11,2022,2022-11-06,72065,10,17095.599609,16.600000,17.000000,156.399994
19931,108998961191900167,Worlds 2022,knockouts,knockouts,1,53.932598,99566404585387054,DRX,DRX,drx,1,108998961199895797,1,6,11,2022,2022-11-06,74697,19,18909.000000,17.000000,16.600000,185.199997

In [4]:
# done once
# df_teams = df[['Team ID', 'Team Name']].drop_duplicates()
# df_teams.reset_index(drop=True)
# df_teams.to_parquet("../data/teams_df.parquet.gzip", compression = "gzip", index=False)

In [33]:
random_idx = random.randint(0, df.shape[0])
df.iloc[random_idx]

Trn ID                                110574243270525539
Trn Name                                     Summer 2023
Stage                                     Regular Season
Section                                   Regular Season
trn_recent_world_msi_region_22_23                      0
league_score                                   58.426998
Team ID                               106857761435870473
Team Name                                      Supernova
Team Acronym                                          SN
Team Slug                                      supernova
useful_team_indicator                                  1
Game ID                               110574243271705412
Outcome                                                0
day                                                   19
month                                                  6
year                                                2023
event_date                           2023-06-19 00:00:00
totalGold_own                                      44045
championsKills_own                                     7
xp_own_avg                                  11232.400391
level_own_avg                                       13.2
level_opp_avg                                       14.6
attackSpeed_own_avg                           157.199997
Name: 15502, dtype: object

In [34]:
# All rankings
# - GLobal (599)
# - MSI (182) --> only the teams which took part in relevant tournaments from a qualifying region

In [35]:
# Tournament rankings
# - Trn ID: 
#     - 108998961191900167 (Worlds) 
#     - 105562822074055437 (non worlds)

In [36]:
# Teams rankings
# - 107581212180071788, 99566404585387054, 106857761435870473 (Put date = 01-01-2023)
# - Same teams with latest available dates

107581212180071788, 99566404585387054, 106857761435870473

In [5]:
# Identify tournament
# - In Global only
# in MSI only

# Teams list
# GLobal
# MSI 

# Teams by date cutof

In [ ]:
teams_df.loc[teams_df['team_id'] == team]['Team Name'].values[0]

In [49]:
df.loc[df['Team ID'] == 109518697660746274 ]

Empty DataFrame
Columns: [Trn ID, Trn Name, Stage, Section, trn_recent_world_msi_region_22_23, league_score, Team ID, Team Name, Team Acronym, Team Slug, useful_team_indicator, Game ID, Outcome, day, month, year, event_date, totalGold_own, championsKills_own, xp_own_avg, level_own_avg, level_opp_avg, attackSpeed_own_avg]
Index: []

In [38]:
df.loc[df['Trn ID'] == 109467087406180264]

,Trn ID,Trn Name,Stage,Section,trn_recent_world_msi_region_22_23,league_score,Team ID,Team Name,Team Acronym,Team Slug,useful_team_indicator,Game ID,Outcome,day,month,year,event_date,totalGold_own,championsKills_own,xp_own_avg,level_own_avg,level_opp_avg,attackSpeed_own_avg
11398,109467087406180264,Spring 2023,Regular Season,Regular Season,0,58.426998,102787200126663579,Giants,GIA,giants,0,109467087407687598,0,17,1,2023,2023-01-17,43506,7,12953.400391,14.400000,15.200000,154.399994
11399,109467087406180264,Spring 2023,Regular Season,Regular Season,0,58.426998,107467794614674479,FnaticTQ,FNTQ,fnatictq,0,109467087407687598,1,17,1,2023,2023-01-17,57532,13,13990.799805,15.200000,14.400000,169.800003
11400,109467087406180264,Spring 2023,Regular Season,Regular Season,0,58.426998,103877625775457850,Movistar Riders,MRS,movistar-riders,0,109467087407687600,1,16,1,2023,2023-01-16,67380,11,17301.800781,16.799999,15.600000,173.000000
11401,109467087406180264,Spring 2023,Regular Season,Regular Season,0,58.426998,107467794614674479,FnaticTQ,FNTQ,fnatictq,0,109467087407687600,0,16,1,2023,2023-01-16,61240,9,15042.799805,15.600000,16.799999,174.399994
11402,109467087406180264,Spring 2023,Regular Season,Regular Season,0,58.426998,105532791598779236,UCAM,UCAM,ucam-esports-club,0,109467087407687602,0,24,1,2023,2023-01-24,50364,11,12627.400391,14.400000,15.600000,172.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11615,109467087406180264,Spring 2023,Playoffs,Playoffs,0,78.651703,103877625775457850,Movistar Riders,MRS,movistar-riders,0,109467087407818880,1,1,4,2023,2023-04-01,60043,23,15069.599609,15.800000,13.400000,160.800003
11616,109467087406180264,Spring 2023,Playoffs,Playoffs,0,78.651703,107467803833323099,Los Heretics,HRTS,team-heretics-sl,0,109467087407818881,0,1,4,2023,2023-04-01,36303,8,8152.399902,11.000000,12.600000,154.000000
11617,109467087406180264,Spring 2023,Playoffs,Playoffs,0,78.651703,103877625775457850,Movistar Riders,MRS,movistar-riders,0,109467087407818881,1,1,4,2023,2023-04-01,46916,18,10107.000000,12.600000,11.000000,185.600006
11618,109467087406180264,Spring 2023,Playoffs,Playoffs,0,78.651703,103877625775457850,Movistar Riders,MRS,movistar-riders,0,109467087407818882,1,1,4,2023,2023-04-01,46440,19,9582.200195,12.200000,11.000000,163.399994
11619,109467087406180264,Spring 2023,Playoffs,Playoffs,0,78.651703,107467803833323099,Los Heretics,HRTS,team-heretics-sl,0,109467087407818882,0,1,4,2023,2023-04-01,32538,6,8078.000000,11.000000,12.200000,148.800003

In [26]:
df.loc[df["Trn ID"] == 108176672283976661]["Trn Name"].values[0]

'LEC Summer 2022'